### ISSUE TITLE
请问用您这个在1.13.3的flink下使用好像是报错的？这是版本原因导致么？

### ISSUE THREAD

**Issue by sty945** [liuhouer/np-flink-connector-jdbc#1]
创建了一个写入mysql的表，出现如下错误的:

```
[ERROR] Could not execute SQL statement. Reason:
java.lang.NoSuchMethodError: org.apache.flink.table.factories.DynamicTableFactory$Context.getCatalogTable()Lorg/apache/flink/table/catalog/CatalogTable;
```

**Comment by liuhouer** [comment]
您发给我的信件已经收到。访问https://northpark.cn/note/list 查看第一条教程，自己动手去获取许可证。                谢谢！

**Comment by liuhouer** [comment]
您好，是版本问题，我是依据flink1.12.1版本编译的

**Comment by sty945** [comment]
> 

您好，不好意思，对这块不太熟悉，想使用oracle jdbc验证一下功能，请问您有1.13.3版本的编译jar包方便分享一下么？

**Comment by liuhouer** [comment]
最近太忙了，你可以参照代码 自行编译一下 或者等我佛系更新

**Comment by hanpi14** [comment]
> > 
> 
> 您好，不好意思，对这块不太熟悉，想使用oracle jdbc验证一下功能，请问您有1.13.3版本的编译jar包方便分享一下么？

您这边1.13.3测试结果怎么样了?

**Comment by liuhouer** [comment]
> > > 
> > 
> > 
> > 您好，不好意思，对这块不太熟悉，想使用oracle jdbc验证一下功能，请问您有1.13.3版本的编译jar包方便分享一下么？
> 
> 您这边1.13.3测试结果怎么样了?

https://github.com/liuhouer/np-flink-connector-jdbc/releases/tag/np-1.13.3
